import { ThemeLayerConfig } from '../../../api/themeLayerConfigApi';

const BASE_URL =
  'https://testnedlasting.geonorge.no/geonorge/Basisdata/DOKFullstendighetsdekningskart/Kartkatalogen/';

export const fullstendighetsdekningConfig: ThemeLayerConfig = {
  categories: [
    {
      id: 'fullstendighetsdekning',
      groupid: 19,
      name: {
        nb: 'Fullstendighetsdekning',
        nn: 'Fullstendigheitsdekning',
        en: 'Completeness coverage',
      },
    },
  ],
  layers: [
    {
      id: 'fd_adresse',
      name: { nb: 'Adresse', nn: 'Adresse', en: 'Address' },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_adresse.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_aktsomhetskart_jord_flomskred',
      name: {
        nb: 'Aktsomhetskart jord- og flomskred',
        nn: 'Aktsomhetskart jord- og flomskred',
        en: 'Susceptibility map earth and water floods',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_aktsomhetskart_jord_flomskred.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_aktsomhetskart_kvikkleireskred',
      name: {
        nb: 'Aktsomhetskart kvikkleireskred',
        nn: 'Aktsomhetskart kvikkleireskred',
        en: 'Susceptibility map quick clay slides',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_aktsomhetskart_kvikkleireskred.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_aktsomhetskart_snoskred',
      name: {
        nb: 'Aktsomhetskart snøskred',
        nn: 'Aktsomhetskart snøskred',
        en: 'Susceptibility map avalanches',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_aktsomhetskart_snoskred.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_akvakulturlokaliteter',
      name: {
        nb: 'Akvakulturlokaliteter',
        nn: 'Akvakulturlokalitetar',
        en: 'Aquaculture sites',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_akvakulturlokaliteter.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_anadrome_laksefisk_strekninger',
      name: {
        nb: 'Anadrome laksefisk strekninger',
        nn: 'Anadrome laksefisk strekningar',
        en: 'Anadromous salmon fish sections',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_anadrome_laksefisk_strekninger.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_ankringsomrader',
      name: {
        nb: 'Ankringsområder',
        nn: 'Ankringsområde',
        en: 'Anchorage areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_ankringsomrader.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_ar50_arealtyper',
      name: {
        nb: 'AR50 arealtyper',
        nn: 'AR50 arealtypar',
        en: 'AR50 land use types',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_ar50_arealtyper.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_arealbruk',
      name: { nb: 'Arealbruk', nn: 'Arealbruk', en: 'Land use' },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_arealbruk.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_banenettverk',
      name: {
        nb: 'Banenettverk',
        nn: 'Banenettverk',
        en: 'Railway network',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_banenettverk.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_barmarksloyper',
      name: {
        nb: 'Barmarksloyper',
        nn: 'Barmarksloyper',
        en: 'Bare ground trails',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_barmarksloyper.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_befolkning_rutenett_1000_2025',
      name: {
        nb: 'Befolkning rutenett 1000m (2025)',
        nn: 'Befolkning rutenett 1000m (2025)',
        en: 'Population grid 1000m (2025)',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_befolkning_rutenett_1000_2025.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_befolkning_rutenett_250_2025',
      name: {
        nb: 'Befolkning rutenett 250m (2025)',
        nn: 'Befolkning rutenett 250m (2025)',
        en: 'Population grid 250m (2025)',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_befolkning_rutenett_250_2025.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_bergrettigheter',
      name: {
        nb: 'Bergrettigheter',
        nn: 'Bergrettar',
        en: 'Mining rights',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_bergrettigheter.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_brannsmitteomrader',
      name: {
        nb: 'Brannsmitteområder',
        nn: 'Brannsmitteområde',
        en: 'Fire risk areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_brannsmitteomrader.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_byggeforbudssoner',
      name: {
        nb: 'Byggeforbudssoner',
        nn: 'Byggeforbudssoner',
        en: 'Building prohibition zones',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_byggeforbudssoner.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_byggerestriksjoner_bra',
      name: {
        nb: 'Byggerestriksjoner',
        nn: 'Byggerestriksjoner',
        en: 'Building restrictions',
      },
      type: 'geojson',
      geojsonUrl:
        BASE_URL + 'dekning_byggerestriksjoner%20%28bra%29.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_bygningspunkt',
      name: {
        nb: 'Bygningspunkt',
        nn: 'Bygningspunkt',
        en: 'Building points',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_bygningspunkt.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_digitale_ortofoto',
      name: {
        nb: 'Digitale ortofoto',
        nn: 'Digitale ortofoto',
        en: 'Digital orthophotos',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_digitale_ortofoto.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_dtm10_utm33',
      name: {
        nb: 'DTM 10 (UTM33)',
        nn: 'DTM 10 (UTM33)',
        en: 'DTM 10 (UTM33)',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_dtm10_utm33.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_dyrkbar_jord',
      name: {
        nb: 'Dyrkbar jord',
        nn: 'Dyrkbar jord',
        en: 'Cultivable land',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_dyrkbar_jord.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_eiendomskart_teig',
      name: {
        nb: 'Eiendomskart teig',
        nn: 'Eigedomskart teig',
        en: 'Property map plots',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_eiendomskart_teig.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_eksplosivanlegg',
      name: {
        nb: 'Eksplosivanlegg',
        nn: 'Eksplosivanlegg',
        en: 'Explosive facilities',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_eksplosivanlegg.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_farlig_stoff_anlegg',
      name: {
        nb: 'Farlig stoff-anlegg',
        nn: 'Farleg stoff-anlegg',
        en: 'Hazardous substance facilities',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_farlig%20stoff-anlegg.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_fiskeplasser_redskap',
      name: {
        nb: 'Fiskeplasser redskap',
        nn: 'Fiskeplassar reiskap',
        en: 'Fishing places and gear',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_fiskeplasser_redskap.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_fiskerihavner',
      name: {
        nb: 'Fiskerihavner',
        nn: 'Fiskerihavner',
        en: 'Fishing harbours',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_fiskerihavner.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_fkb_ar5',
      name: { nb: 'FKB-AR5', nn: 'FKB-AR5', en: 'FKB-AR5' },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_fkb-ar5.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_fkb_arealbruk',
      name: {
        nb: 'FKB-Arealbruk',
        nn: 'FKB-Arealbruk',
        en: 'FKB-Land use',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_fkb-arealbruk.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_fkb_bygnanlegg',
      name: {
        nb: 'FKB-Bygnanlegg',
        nn: 'FKB-Bygnanlegg',
        en: 'FKB-Building structures',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_fkb-bygnanlegg.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_fkb_hoydekurve',
      name: {
        nb: 'FKB-Høydekurve',
        nn: 'FKB-Høgdekurve',
        en: 'FKB-Contour lines',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_fkb-hoydekurve.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_fkb_traktorvegsti',
      name: {
        nb: 'FKB-Traktorveg/sti',
        nn: 'FKB-Traktorveg/sti',
        en: 'FKB-Tractor roads/trails',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_fkb-traktorvegsti.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_fkb_veg',
      name: { nb: 'FKB-Veg', nn: 'FKB-Veg', en: 'FKB-Roads' },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_fkb-veg.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_fkb_bygning',
      name: {
        nb: 'FKB-Bygning',
        nn: 'FKB-Bygning',
        en: 'FKB-Buildings',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_fkb_bygning.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_fkb_vann',
      name: { nb: 'FKB-Vann', nn: 'FKB-Vatn', en: 'FKB-Water' },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_fkb_vann.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_flom_aktsomhetsomrader',
      name: {
        nb: 'Flom aktsomhetsområder',
        nn: 'Flom aktsomhetsområde',
        en: 'Flood susceptibility areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_flom_aktsomhetsomrader.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_flomsoner',
      name: { nb: 'Flomsoner', nn: 'Flomsoner', en: 'Flood zones' },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_flomsoner.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_flyttlei',
      name: {
        nb: 'Flyttlei',
        nn: 'Flyttlei',
        en: 'Reindeer migration routes',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_flyttlei.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_forenklet_elveg2',
      name: {
        nb: 'Forenklet Elveg 2',
        nn: 'Forenkla Elveg 2',
        en: 'Simplified road network 2',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_forenklet_elveg2.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_forsvarets_skyte_ovingsfelt_land',
      name: {
        nb: 'Forsvarets skyte- og øvingsfelt (land)',
        nn: 'Forsvaret skyte- og øvingsfelt (land)',
        en: 'Military shooting and training areas (land)',
      },
      type: 'geojson',
      geojsonUrl:
        BASE_URL + 'dekning_forsvarets_skyte_ovingsfelt_land.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_forsvarets_skyte_ovingsfelt_sjo',
      name: {
        nb: 'Forsvarets skyte- og øvingsfelt (sjø)',
        nn: 'Forsvaret skyte- og øvingsfelt (sjø)',
        en: 'Military shooting and training areas (sea)',
      },
      type: 'geojson',
      geojsonUrl:
        BASE_URL + 'dekning_forsvarets_skyte_ovingsfelt_sjo.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_geologisk_arv',
      name: {
        nb: 'Geologisk arv',
        nn: 'Geologisk arv',
        en: 'Geological heritage',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_geologisk_arv.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_grus_pukk',
      name: {
        nb: 'Grus og pukk',
        nn: 'Grus og pukk',
        en: 'Gravel and crushed rock',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_grus_pukk.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_gyteomrader',
      name: {
        nb: 'Gyteområder',
        nn: 'Gyteområde',
        en: 'Spawning areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_gyteomrader.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_hovedled_biled',
      name: {
        nb: 'Hovedled/biled',
        nn: 'Hovudled/biled',
        en: 'Main/secondary shipping lanes',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_hovedled_biled.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_hovedled_biled_arealgrense',
      name: {
        nb: 'Hovedled/biled arealgrense',
        nn: 'Hovudled/biled arealgrense',
        en: 'Shipping lane area boundaries',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_hovedled_biled_arealgrense.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_inngrepsfri_natur_i_norge',
      name: {
        nb: 'Inngrepsfri natur i Norge',
        nn: 'Inngrepsfri natur i Noreg',
        en: 'Wilderness areas in Norway',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_inngrepsfri_natur_i_norge.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_kommuner',
      name: {
        nb: 'Kommuner',
        nn: 'Kommunar',
        en: 'Municipalities',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_kommuner.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_lassettingsplasser',
      name: {
        nb: 'Lassettingsplasser',
        nn: 'Lassettingsplassar',
        en: 'Loading places',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_lassettingsplasser.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_marin_grense',
      name: {
        nb: 'Marin grense',
        nn: 'Marin grense',
        en: 'Marine boundary',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_marin_grense.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_markagrensen',
      name: {
        nb: 'Markagrensen',
        nn: 'Markagrensa',
        en: 'Forest boundary (Marka)',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_markagrensen.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_matrikkelen',
      name: {
        nb: 'Matrikkelen',
        nn: 'Matrikkelen',
        en: 'Property register',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_matrikkelen.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_n20_kartdata',
      name: {
        nb: 'N20 kartdata',
        nn: 'N20 kartdata',
        en: 'N20 map data',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_n20%20kartdata.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_n20bygning',
      name: {
        nb: 'N20 bygning',
        nn: 'N20 bygning',
        en: 'N20 buildings',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_n20bygning.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_n250',
      name: { nb: 'N250', nn: 'N250', en: 'N250' },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_n250.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_n5_kartdata',
      name: {
        nb: 'N5 kartdata',
        nn: 'N5 kartdata',
        en: 'N5 map data',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_n5%20kartdata.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_n5_presentasjonsdata',
      name: {
        nb: 'N5 presentasjonsdata',
        nn: 'N5 presentasjonsdata',
        en: 'N5 presentation data',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_n5%20presentasjonsdata.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_n5_raster',
      name: { nb: 'N5 raster', nn: 'N5 raster', en: 'N5 raster' },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_n5%20raster.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_n50',
      name: { nb: 'N50', nn: 'N50', en: 'N50' },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_n50.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_nasjonale_laksefjorder',
      name: {
        nb: 'Nasjonale laksefjorder',
        nn: 'Nasjonale laksefjordar',
        en: 'National salmon fjords',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_nasjonale_laksefjorder.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_naturvernomrader',
      name: {
        nb: 'Naturvernområder',
        nn: 'Naturvernområde',
        en: 'Nature reserves',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_naturvernomrader.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_naturvernomrader_foreslatte',
      name: {
        nb: 'Naturvernområder (foreslåtte)',
        nn: 'Naturvernområde (foreslåtte)',
        en: 'Nature reserves (proposed)',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_naturvernomrader_foreslatte.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_navigasjonsinstallasjoner',
      name: {
        nb: 'Navigasjonsinstallasjoner',
        nn: 'Navigasjonsinstallasjonar',
        en: 'Navigation installations',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_navigasjonsinstallasjoner.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_ramsaromrader',
      name: {
        nb: 'Ramsarområder',
        nn: 'Ramsarområde',
        en: 'Ramsar areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_ramsaromrader.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reinbeitedistrikt',
      name: {
        nb: 'Reinbeitedistrikt',
        nn: 'Reinbeitedistrikt',
        en: 'Reindeer grazing districts',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reinbeitedistrikt.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reinbeiteomrade',
      name: {
        nb: 'Reinbeiteområde',
        nn: 'Reinbeiteområde',
        en: 'Reindeer grazing areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reinbeiteomrade.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_avtaleomrade',
      name: {
        nb: 'Reindrift: Avtaleområde',
        nn: 'Reindrift: Avtaleområde',
        en: 'Reindeer herding: Agreement areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_avtaleomrade.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_beitehage',
      name: {
        nb: 'Reindrift: Beitehage',
        nn: 'Reindrift: Beitehage',
        en: 'Reindeer herding: Pasture enclosures',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_beitehage.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_ekspropriasjonsomrade',
      name: {
        nb: 'Reindrift: Ekspropriasjonsområde',
        nn: 'Reindrift: Ekspropriasjonsområde',
        en: 'Reindeer herding: Expropriation areas',
      },
      type: 'geojson',
      geojsonUrl:
        BASE_URL + 'dekning_reindrift_ekspropriasjonsomrade.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_hostbeite',
      name: {
        nb: 'Reindrift: Høstbeite',
        nn: 'Reindrift: Haustbeite',
        en: 'Reindeer herding: Autumn pasture',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_hostbeite.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_hostvinterbeite',
      name: {
        nb: 'Reindrift: Høst-/vinterbeite',
        nn: 'Reindrift: Haust-/vinterbeite',
        en: 'Reindeer herding: Autumn/winter pasture',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_hostvinterbeite.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_konsesjonsomrade',
      name: {
        nb: 'Reindrift: Konsesjonsområde',
        nn: 'Reindrift: Konsesjonsområde',
        en: 'Reindeer herding: Concession areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_konsesjonsomrade.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_konvensjonsomrade',
      name: {
        nb: 'Reindrift: Konvensjonsområde',
        nn: 'Reindrift: Konvensjonsområde',
        en: 'Reindeer herding: Convention areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_konvensjonsomrade.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_oppsamlingsomrade',
      name: {
        nb: 'Reindrift: Oppsamlingsområde',
        nn: 'Reindrift: Oppsamlingsområde',
        en: 'Reindeer herding: Gathering areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_oppsamlingsomrade.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_restriksjonsomrade',
      name: {
        nb: 'Reindrift: Restriksjonsområde',
        nn: 'Reindrift: Restriksjonsområde',
        en: 'Reindeer herding: Restriction areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_restriksjonsomrade.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_samebyavtale',
      name: {
        nb: 'Reindrift: Samebyavtale',
        nn: 'Reindrift: Samebyavtale',
        en: 'Reindeer herding: Sameby agreements',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_samebyavtale.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_samebyrettsavgjorelse',
      name: {
        nb: 'Reindrift: Samebyrettsavgjørelse',
        nn: 'Reindrift: Samebyrettsavgjerdsle',
        en: 'Reindeer herding: Sameby legal decisions',
      },
      type: 'geojson',
      geojsonUrl:
        BASE_URL + 'dekning_reindrift_samebyrettsavgjorelse.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_siidaomrade',
      name: {
        nb: 'Reindrift: Siidaområde',
        nn: 'Reindrift: Siidaområde',
        en: 'Reindeer herding: Siida areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_siidaomrade.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_sommerbeite',
      name: {
        nb: 'Reindrift: Sommerbeite',
        nn: 'Reindrift: Sommarbeite',
        en: 'Reindeer herding: Summer pasture',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_sommerbeite.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_trekklei',
      name: {
        nb: 'Reindrift: Trekklei',
        nn: 'Reindrift: Trekklei',
        en: 'Reindeer herding: Migration routes',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_trekklei.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_varbeite',
      name: {
        nb: 'Reindrift: Vårbeite',
        nn: 'Reindrift: Vårbeite',
        en: 'Reindeer herding: Spring pasture',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_varbeite.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindrift_vinterbeiteomrade',
      name: {
        nb: 'Reindrift: Vinterbeiteområde',
        nn: 'Reindrift: Vinterbeiteområde',
        en: 'Reindeer herding: Winter pasture areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindrift_vinterbeiteomrade.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_reindriftsanlegg',
      name: {
        nb: 'Reindriftsanlegg',
        nn: 'Reindriftsanlegg',
        en: 'Reindeer herding facilities',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_reindriftsanlegg.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_restriksjonsplaner_avinor',
      name: {
        nb: 'Restriksjonsplaner Avinors lufthavner',
        nn: 'Restriksjonsplanar Avinors lufthamner',
        en: 'Restriction plans Avinor airports',
      },
      type: 'geojson',
      geojsonUrl:
        BASE_URL +
        'dekning_restriksjonsplaner%20for%20avinors%20lufthavner.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_sjokart_dybdedata',
      name: {
        nb: 'Sjøkart dybdedata',
        nn: 'Sjøkart djupnedata',
        en: 'Nautical chart depth data',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_sjokart_dybdedata.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_sjokart_raster_hovedkart',
      name: {
        nb: 'Sjøkart raster (hovedkart)',
        nn: 'Sjøkart raster (hovudkart)',
        en: 'Nautical chart raster (main map)',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_sjokart_raster_hovedkart.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_skredhendelser',
      name: {
        nb: 'Skredhendelser',
        nn: 'Skredhendingar',
        en: 'Landslide events',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_skredhendelser.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_snoscooterloyper',
      name: {
        nb: 'Snøscooterloyper',
        nn: 'Snøscooterloyper',
        en: 'Snowmobile trails',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_snoscooterloyper.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_spr_strandsonen',
      name: {
        nb: 'SPR Strandsonen',
        nn: 'SPR Strandsonen',
        en: 'SPR Coastal zone',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_spr_strandsonen.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_statlig_sikra_friluftsomrader',
      name: {
        nb: 'Statlig sikra friluftsområder',
        nn: 'Statleg sikra friluftsområde',
        en: 'State-secured outdoor recreation areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_statlig_sikra_friluftsomrader.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_stedsnavn_forenklet',
      name: {
        nb: 'Stedsnavn (forenklet)',
        nn: 'Stadnamn (forenkla)',
        en: 'Place names (simplified)',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_stedsnavn_forenklet.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_steinsprang_aktsomhetsomr',
      name: {
        nb: 'Steinsprang aktsomhetsområder',
        nn: 'Steinsprang aktsomhetsområde',
        en: 'Rockfall susceptibility areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_steinsprang_aktsomhetsomr.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_stormflo_havniva',
      name: {
        nb: 'Stormflo havnivå',
        nn: 'Stormflo havnivå',
        en: 'Storm surge sea levels',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_stormflo_havniva.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_storulykkeanlegg',
      name: {
        nb: 'Storulykkeanlegg',
        nn: 'Storulykkeanlegg',
        en: 'Major accident facilities',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_storulykkeanlegg.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_stoysoner_forsvarets_flyplasser',
      name: {
        nb: 'Støysoner forsvarets flyplasser',
        nn: 'Støysoner forsvaret sine flyplassar',
        en: 'Noise zones military airports',
      },
      type: 'geojson',
      geojsonUrl:
        BASE_URL + 'dekning_stoysoner_forsvarets_flyplasser.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_stoysoner_lufthavn',
      name: {
        nb: 'Støysoner lufthavn',
        nn: 'Støysoner lufthamn',
        en: 'Noise zones airports',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_stoysoner_lufthavn.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_stoysoner_skyte_og_ovingsfelt',
      name: {
        nb: 'Støysoner skyte- og øvingsfelt',
        nn: 'Støysoner skyte- og øvingsfelt',
        en: 'Noise zones shooting and training areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_stoysoner_skyte_og_ovingsfelt.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_tare_hostefelt',
      name: {
        nb: 'Tare høstefelt',
        nn: 'Tare høstefelt',
        en: 'Kelp harvesting areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_tare_hostefelt.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_tettsteder_2025',
      name: {
        nb: 'Tettsteder (2025)',
        nn: 'Tettstader (2025)',
        en: 'Urban settlements (2025)',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_tettsteder_2025.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_tilgjengelighet',
      name: {
        nb: 'Tilgjengelighet',
        nn: 'Tilgjenge',
        en: 'Accessibility',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_tilgjengelighet.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_trafikkmengde',
      name: {
        nb: 'Trafikkmengde',
        nn: 'Trafikkmengde',
        en: 'Traffic volume',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_trafikkmengde.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_trafikkulykker',
      name: {
        nb: 'Trafikkulykker',
        nn: 'Trafikkulykker',
        en: 'Traffic accidents',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_trafikkulykker.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_tur_og_friluftsruter',
      name: {
        nb: 'Tur og friluftsruter',
        nn: 'Tur og friluftsruter',
        en: 'Hiking and outdoor recreation routes',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_tur_og_friluftsruter.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_vannforekomster',
      name: {
        nb: 'Vannforekomster',
        nn: 'Vassdrag',
        en: 'Water bodies',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_vannforekomster.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_vannkraft_utbygd_ikkeutbygd',
      name: {
        nb: 'Vannkraft (utbygd/ikke utbygd)',
        nn: 'Vasskraft (utbygd/ikkje utbygd)',
        en: 'Hydropower (developed/undeveloped)',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_vannkraft_utbygd_ikkeutbygd.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_vassdrag_verneplan',
      name: {
        nb: 'Vassdrag verneplan',
        nn: 'Vassdrag verneplan',
        en: 'Watercourse protection plan',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_vassdrag_verneplan.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_verneverdig_tette_trehusmiljoer',
      name: {
        nb: 'Verneverdig tette trehus',
        nn: 'Verneverdig tette trehus',
        en: 'Valuable dense wooden buildings',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_verneverdig_tette_trehusmiljoer.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_villreinomrader',
      name: {
        nb: 'Villreinområder',
        nn: 'Villreinområde',
        en: 'Wild reindeer areas',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_villreinomrader.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
    {
      id: 'fd_vindkraftverk',
      name: {
        nb: 'Vindkraftverk',
        nn: 'Vindkraftverk',
        en: 'Wind power plants',
      },
      type: 'geojson',
      geojsonUrl: BASE_URL + 'dekning_vindkraftverk.geojson',
      sourceEpsg: 'EPSG:25833',
      styleType: 'dekningsstatus',
      categoryId: 'fullstendighetsdekning',
      groupid: 19,
    },
  ],
};
