import { ThemeLayerConfig } from '../../../api/themeLayerConfigApi';

export const sjoConfig: ThemeLayerConfig = {
  categories: [
    {
      id: 'sjo',
      groupid: 14,
      name: {
        nb: 'Sjø',
        nn: 'Sjø',
        en: 'Sea',
      },
    },
    {
      id: 'sjo_dybdedatakvalitet',
      groupid: 14,
      name: {
        nb: 'Dybdedatakvalitet',
        nn: 'Djupdatakvalitet',
        en: 'Depth data quality',
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.dybdedatakvalitet_navigasjon',
      parentId: 'sjo',
    },
    {
      id: 'sjo_farlige_bolger',
      groupid: 14,
      name: {
        nb: 'Farlige bølger',
        nn: 'Farlege bølgjer',
        en: 'Dangerous waves',
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.farlige_bolger',
      parentId: 'sjo',
    },
    {
      id: 'sjo_marine_grunnkart',
      groupid: 14,
      name: {
        nb: 'Marine grunnkart',
        nn: 'Marine grunnkart',
        en: 'Marine base maps',
      },
      wmsUrl: 'https://geo.ngu.no/mapserver/MarineGrunnkartWMS',
      parentId: 'sjo',
    },
    {
      id: 'sjo_nmg',
      groupid: 14,
      name: {
        nb: 'Norges maritime grenser',
        nn: 'Noregs maritime grenser',
        en: "Norway's maritime borders",
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.nmg',
      parentId: 'sjo',
    },
  ],
  layers: [
    // --- Dybdedatakvalitet layers ---
    {
      id: 'sjoDybdedatakvalitetSjokart',
      name: {
        nb: 'Dybdedatakvalitet sjøkart',
        nn: 'Djupdatakvalitet sjøkart',
        en: 'Depth data quality nautical chart',
      },
      layers: 'Dybdedatakvalitet_sjokart',
      categoryId: 'sjo_dybdedatakvalitet',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoIkkeSjomalt',
      name: {
        nb: 'Ikke sjømålt',
        nn: 'Ikkje sjømålt',
        en: 'Not surveyed',
      },
      layers: 'IkkeSjomalt',
      categoryId: 'sjo_dybdedatakvalitet',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },

    // --- Farlige bølger layers ---
    {
      id: 'sjoFarligeBolger',
      name: {
        nb: 'Farlige bølger',
        nn: 'Farlege bølgjer',
        en: 'Dangerous waves',
      },
      layers: 'Farlige_bolger',
      categoryId: 'sjo_farlige_bolger',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoAktsomhetsomradeFarligeBolger',
      name: {
        nb: 'Aktsomhetsområde farlige bølger',
        nn: 'Aktsemdområde farlege bølgjer',
        en: 'Precautionary area dangerous waves',
      },
      layers: 'AktsomhetsomradeFarligeBolger',
      categoryId: 'sjo_farlige_bolger',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },

    // --- Marine grunnkart layers ---
    {
      id: 'sjoDybdeforhold',
      name: {
        nb: 'Dybdeforhold',
        nn: 'Djupneforhold',
        en: 'Depth conditions',
      },
      layers: 'Dybdeforhold',
      categoryId: 'sjo_marine_grunnkart',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoHelning',
      name: {
        nb: 'Helning',
        nn: 'Helling',
        en: 'Slope',
      },
      layers: 'Helning',
      categoryId: 'sjo_marine_grunnkart',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoHelningOver30',
      name: {
        nb: 'Helning over 30°',
        nn: 'Helling over 30°',
        en: 'Slope over 30°',
      },
      layers: 'Helning_over_30',
      categoryId: 'sjo_marine_grunnkart',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoNaturtyper',
      name: {
        nb: 'Naturtyper',
        nn: 'Naturtypar',
        en: 'Nature types',
      },
      layers: 'Naturtyper',
      categoryId: 'sjo_marine_grunnkart',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoKornstorrelseDet',
      name: {
        nb: 'Kornstørrelse detaljert',
        nn: 'Kornstorleik detaljert',
        en: 'Grain size detailed',
      },
      layers: 'Kornstorrelse_Det',
      categoryId: 'sjo_marine_grunnkart',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoGravbarhet',
      name: {
        nb: 'Gravbarhet',
        nn: 'Gravbarheit',
        en: 'Excavability',
      },
      layers: 'Gravbarhet',
      categoryId: 'sjo_marine_grunnkart',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoBunnfellingsomrader',
      name: {
        nb: 'Bunnfellingsområder',
        nn: 'Botnfellingsområde',
        en: 'Sedimentation areas',
      },
      layers: 'Bunnfellingsomrader',
      categoryId: 'sjo_marine_grunnkart',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoAnkringsforhold',
      name: {
        nb: 'Ankringsforhold',
        nn: 'Ankringsforhold',
        en: 'Anchoring conditions',
      },
      layers: 'Ankringsforhold',
      categoryId: 'sjo_marine_grunnkart',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },

    // --- Norges maritime grenser layers ---
    {
      id: 'sjoGrunnlinje',
      name: {
        nb: 'Grunnlinje',
        nn: 'Grunnlinje',
        en: 'Baseline',
      },
      layers: 'Grunnlinje',
      categoryId: 'sjo_nmg',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoTerritorialgrense',
      name: {
        nb: 'Territorialgrense',
        nn: 'Territorialgrense',
        en: 'Territorial border',
      },
      layers: 'Territorialgrense',
      categoryId: 'sjo_nmg',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoTilstotendeSone',
      name: {
        nb: 'Tilstøtende sone',
        nn: 'Tilstøytande sone',
        en: 'Contiguous zone',
      },
      layers: 'Tilstotende_sone',
      categoryId: 'sjo_nmg',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoNorgesOkonomiskeSone',
      name: {
        nb: 'Norges økonomiske sone',
        nn: 'Noregs økonomiske sone',
        en: "Norway's economic zone",
      },
      layers: 'Norges_okonomiske_sone',
      categoryId: 'sjo_nmg',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoFiskevernsonen',
      name: {
        nb: 'Fiskevernsonen ved Svalbard',
        nn: 'Fiskevernsona ved Svalbard',
        en: 'Fisheries protection zone Svalbard',
      },
      layers: 'Fiskevernsonen_ved_Svalbard',
      categoryId: 'sjo_nmg',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoFiskerisonen',
      name: {
        nb: 'Fiskerisonen ved Jan Mayen',
        nn: 'Fiskerisona ved Jan Mayen',
        en: 'Fisheries zone Jan Mayen',
      },
      layers: 'Fiskerisonen_ved_Jan_Mayen',
      categoryId: 'sjo_nmg',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoKontinentalsokkel',
      name: {
        nb: 'Norges kontinentalsokkel',
        nn: 'Noregs kontinentalsokkel',
        en: "Norway's continental shelf",
      },
      layers: 'Norges_kontinentalsokkel',
      categoryId: 'sjo_nmg',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
    {
      id: 'sjoAvtaltAvgrensningslinje',
      name: {
        nb: 'Avtalt avgrensningslinje',
        nn: 'Avtalt avgrensningslinje',
        en: 'Agreed delimitation line',
      },
      layers: 'Avtalt_avgrensningslinje',
      categoryId: 'sjo_nmg',
      groupid: 14,
      queryable: false,
      useLegendGraphic: true,
    },
  ],
};
