import { ThemeLayerConfig } from '../../../api/themeLayerConfigApi';

export const tilgjengelighetConfig: ThemeLayerConfig = {
  categories: [
    {
      id: 'tilgjengelighet',
      groupid: 11,
      name: {
        nb: 'Tilgjengelighet',
        nn: 'Tilgjenge',
        en: 'Accessibility',
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.tilgjengelighet3',
      infoFormat: 'application/vnd.ogc.gml',
      featureInfoImageBaseUrl:
        'https://data.kartverket.no/tilgjengelighet/tilgjengelighet',
      featureInfoFields: [
        {
          name: 'tilgjengvurderingrulleauto',
          type: 'symbol',
          alias: 'Rullestol',
          baseurl:
            'https://data.kartverket.no/tilgjengelighet/symboler/rullestol/',
          filetype: 'png',
        },
        {
          name: 'tilgjengvurderingelrullestol',
          type: 'symbol',
          alias: 'El-rullestol',
          baseurl:
            'https://data.kartverket.no/tilgjengelighet/symboler/rullestol_el/',
          filetype: 'png',
        },
        {
          name: 'tilgjengvurderingelrull',
          type: 'symbol',
          alias: 'El-rullestol',
          baseurl:
            'https://data.kartverket.no/tilgjengelighet/symboler/rullestol_el/',
          filetype: 'png',
        },
        {
          name: 'tilgjengvurderingsyn',
          type: 'symbol',
          alias: 'Syn',
          baseurl: 'https://data.kartverket.no/tilgjengelighet/symboler/syn/',
          filetype: 'png',
        },
        {
          name: 'bildefil1',
          type: 'picture',
          alias: 'Bilde 1',
          baseurl:
            'https://data.kartverket.no/tilgjengelighet/tilgjengelighet/',
        },
        {
          name: 'bildefil2',
          type: 'picture',
          alias: 'Bilde 2',
          baseurl:
            'https://data.kartverket.no/tilgjengelighet/tilgjengelighet/',
        },
        {
          name: 'bildefil3',
          type: 'picture',
          alias: 'Bilde 3',
          baseurl:
            'https://data.kartverket.no/tilgjengelighet/tilgjengelighet/',
        },
        {
          name: 'linkskjema',
          type: 'link',
          alias: 'Skjema',
          baseurl:
            'https://data.kartverket.no/tilgjengelighet/friluft-skjema-FRL-2012/',
        },
        {
          name: 'linkbilde',
          type: 'link',
          alias: 'Bilde (lenke)',
          baseurl:
            'https://data.kartverket.no/tilgjengelighet/friluft-skjema-FRL-2012/',
        },
        {
          name: 'lenke',
          type: 'link',
          alias: 'Lenke',
          baseurl: '',
        },
        {
          name: 'forstedatafangstdato',
          alias: 'Registrert',
        },
        {
          name: 'datafangstdato',
          alias: 'Oppdatert',
        },
        {
          name: 'navn',
          alias: 'Navn',
        },
        {
          name: 'eier',
          alias: 'Eier',
        },
        {
          name: 'veitype',
          alias: 'Veitype',
        },
        {
          name: 'spesialfotrutetype',
          alias: 'Spesial fotrutetype',
        },
        {
          name: 'dekkemateriale',
          alias: 'Dekke materiale',
        },
        {
          name: 'plankeavstand',
          alias: 'Plankeavstand',
          unit: 'cm',
        },
        {
          name: 'dekketilstand',
          alias: 'Dekke tilstand',
        },
        {
          name: 'dekkefasthet',
          alias: 'Dekke fasthet',
        },
        {
          name: 'bredde',
          alias: 'Bredde',
          unit: 'cm',
        },
        {
          name: 'stigning',
          alias: 'Stigning',
          unit: '°',
        },
        {
          name: 'tverrfall',
          alias: 'Tverrfall',
          unit: '°',
        },
        {
          name: 'belysning',
          alias: 'Belysning',
        },
        {
          name: 'frihoyde',
          alias: 'Fri høyde',
        },
        {
          name: 'ledelinje',
          alias: 'Ledelinje',
        },
        {
          name: 'kommentar',
          alias: 'Kommentar',
        },
        {
          name: 'objektnr',
          alias: 'Objekt ID',
        },
        {
          name: 'lokalid',
          alias: 'Lokal ID',
        },
        {
          name: 'rampebredde',
          alias: 'Rampe bredde',
          unit: 'cm',
        },
        {
          name: 'rampelengde',
          alias: 'Rampelengde',
          unit: 'cm',
        },
        {
          name: 'rampestigning',
          alias: 'Rampe stigning',
          unit: '°',
        },
        {
          name: 'rampeterskel',
          alias: 'Rampe terskel',
          unit: 'cm',
        },
        {
          name: 'rampetilgjengelig',
          alias: 'Rampe tilgjengelig',
        },
        {
          name: 'handlist',
          alias: 'Håndlist',
        },
        {
          name: 'handlisthoydeovre',
          alias: 'Håndlist høyde øvre',
          unit: 'cm',
        },
        {
          name: 'handlisthoydenedre',
          alias: 'Håndlist høyde nedre',
          unit: 'cm',
        },
        {
          name: 'diameter',
          alias: 'Diameter',
          unit: 'cm',
        },
        {
          name: 'breddeinngang',
          alias: 'Inngang bredde',
          unit: 'cm',
        },
        {
          name: 'hoydeinngang',
          alias: 'Inngang høyde',
          unit: 'cm',
        },
        {
          name: 'terskelhoyde',
          alias: 'Terskel høyde',
          unit: 'cm',
        },
        {
          name: 'flytebrygge',
          alias: 'Flytebrygge',
        },
        {
          name: 'rekkverk',
          alias: 'Rekkverk',
        },
        {
          name: 'stoppkant',
          alias: 'Stoppkant',
        },
        {
          name: 'stoppkanthoyde',
          alias: 'Stoppkant høyde',
          unit: 'cm',
        },
        {
          name: 'skiltet',
          alias: 'Skiltet',
        },
        {
          name: 'merket',
          alias: 'Merket',
        },
        {
          name: 'avstandfasilitet',
          alias: 'Avstand fasilitet',
          unit: 'm',
        },
        {
          name: 'bredde_hc',
          alias: 'Bredde HC',
          unit: 'cm',
        },
        {
          name: 'lengde_hc',
          alias: 'Lengde HC',
          unit: 'cm',
        },
        {
          name: 'avgift',
          alias: 'Avgift',
        },
        {
          name: 'hoyde_kantsten',
          alias: 'Høyde kantsten',
          unit: 'cm',
        },
        {
          name: 'tilgjengeligautomat',
          alias: 'Tilgjengelig automat',
        },
        {
          name: 'kapasitetpersonbiler',
          alias: 'Kapasitet personbiler',
        },
        {
          name: 'antalluu',
          alias: 'Antall UU',
        },
        {
          name: 'naturbaseid',
          alias: 'Naturbase ID',
        },
        {
          name: 'hcparkeringsplass',
          alias: 'HC-parkeringsplass',
        },
        {
          name: 'toalett',
          alias: 'Toalett',
        },
        {
          name: 'turvei',
          alias: 'Turvei',
        },
        {
          name: 'baderampe',
          alias: 'Baderampe',
        },
        {
          name: 'fiskeplass',
          alias: 'Fiskeplass',
        },
        {
          name: 'grillbalplass',
          alias: 'Grillbålplass',
        },
        {
          name: 'sittegruppe',
          alias: 'Sittegruppe',
        },
        {
          name: 'gapahuk',
          alias: 'Gapahuk',
        },
        {
          name: 'informasjon',
          alias: 'Informasjon',
        },
        {
          name: 'sperrebom',
          alias: 'Sperrebom',
        },
        {
          name: 'sperrebomtilgjengelig',
          alias: 'Sperrebom tilgjengelig',
        },
        {
          name: 'dobbelspor',
          alias: 'Dobbelspor',
        },
        {
          name: 'forbedringsforslag',
          alias: 'Forbedringsforslag',
        },
        {
          name: 'plasstype',
          alias: 'Plasstype',
        },
      ],
    },
    {
      id: 'accessibilityVillageWheelchair',
      groupid: 6,
      name: {
        nb: 'Tettsted - Rullestol',
        nn: 'Tettstad - Rullestol',
        en: 'Village - Wheelchair',
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.tilgjengelighet3',
      parentId: 'tilgjengelighet',
    },
    {
      id: 'accessibilityVillageElectricWheelchair',
      groupid: 9,
      name: {
        nb: 'Tettsted - El-rullestol',
        nn: 'Tettstad - El-rullestol',
        en: 'Village - Electric wheelchair',
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.tilgjengelighet3',
      parentId: 'tilgjengelighet',
    },
    {
      id: 'accessibilityVillageSight',
      groupid: 8,
      name: {
        nb: 'Tettsted - Syn',
        nn: 'Tettstad - Syn',
        en: 'Village - Sight',
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.tilgjengelighet3',
      parentId: 'tilgjengelighet',
    },
    {
      id: 'accessibilityRecreationWheelchair',
      groupid: 5,
      name: {
        nb: 'Friluft - Rullestol',
        nn: 'Friluft - Rullestol',
        en: 'Recreation - Wheelchair',
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.tilgjengelighet3',
      parentId: 'tilgjengelighet',
    },
    {
      id: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      name: {
        nb: 'Friluft - El-rullestol',
        nn: 'Friluft - El-rullestol',
        en: 'Recreation - Electric wheelchair',
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.tilgjengelighet3',
      parentId: 'tilgjengelighet',
    },
    {
      id: 'accessibilityRecreationSight',
      groupid: 3,
      name: {
        nb: 'Friluft - Syn',
        nn: 'Friluft - Syn',
        en: 'Recreation - Sight',
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.tilgjengelighet3',
      parentId: 'tilgjengelighet',
    },
    {
      id: 'accessibilityShared',
      groupid: 10,
      name: {
        nb: 'Felles',
        nn: 'Felles',
        en: 'Shared',
      },
      wmsUrl: 'https://wms.geonorge.no/skwms1/wms.tilgjengelighet3',
      parentId: 'tilgjengelighet',
    },
  ],
  layers: [
    {
      id: '6_t_parkeringsomrade_r',
      name: {
        nb: 'Parkerings område',
        nn: 'Parkerings område',
        en: 'Parking area',
      },
      layers: 't_parkeringsomrade_r',
      categoryId: 'accessibilityVillageWheelchair',
      groupid: 6,
      legacyId: '1011',
      queryable: true,
    },
    {
      id: '6_t_vei_r',
      name: {
        nb: 'Vei',
        nn: 'Vei',
        en: 'Road',
      },
      layers: 't_vei_r',
      categoryId: 'accessibilityVillageWheelchair',
      groupid: 6,
      legacyId: '1012',
      queryable: true,
    },
    {
      id: '6_t_HC_parkering_r',
      name: {
        nb: 'HC-parkering',
        nn: 'HC-parkering',
        en: 'HC-parking',
      },
      layers: 't_HC_parkering_r',
      categoryId: 'accessibilityVillageWheelchair',
      groupid: 6,
      legacyId: '1013',
      queryable: true,
    },
    {
      id: '6_t_inngangbygg_r_01',
      name: {
        nb: 'Inngang bygg',
        nn: 'Inngang bygg',
        en: 'Bulding entrance',
      },
      layers: 't_inngangbygg_r_01',
      categoryId: 'accessibilityVillageWheelchair',
      groupid: 6,
      legacyId: '1014',
      queryable: true,
    },
    {
      id: '9_t_parkeringsomrade_el',
      name: {
        nb: 'Parkerings område',
        nn: 'Parkerings område',
        en: 'Parking area',
      },
      layers: 't_parkeringsomrade_el',
      categoryId: 'accessibilityVillageElectricWheelchair',
      groupid: 9,
      legacyId: '1015',
      queryable: true,
    },
    {
      id: '9_t_vei_el',
      name: {
        nb: 'Vei',
        nn: 'Vei',
        en: 'Road',
      },
      layers: 't_vei_el',
      categoryId: 'accessibilityVillageElectricWheelchair',
      groupid: 9,
      legacyId: '1016',
      queryable: true,
    },
    {
      id: '9_t_HC_parkering_el',
      name: {
        nb: 'HC-parkering',
        nn: 'HC-parkering',
        en: 'HC-parking',
      },
      layers: 't_HC_parkering_el',
      categoryId: 'accessibilityVillageElectricWheelchair',
      groupid: 9,
      legacyId: '1017',
      queryable: true,
    },
    {
      id: '9_t_inngangbygg_r_02',
      name: {
        nb: 'Inngang bygg',
        nn: 'Inngang bygg',
        en: 'Bulding entrance',
      },
      layers: 't_inngangbygg_r_02',
      categoryId: 'accessibilityVillageElectricWheelchair',
      groupid: 9,
      legacyId: '1018',
      queryable: true,
    },
    {
      id: '8_t_parkeringsomrade',
      name: {
        nb: 'Parkerings område',
        nn: 'Parkerings område',
        en: 'Parking area',
      },
      layers: 't_parkeringsomrade',
      categoryId: 'accessibilityVillageSight',
      groupid: 8,
      legacyId: '1019',
      queryable: true,
    },
    {
      id: '8_t_vei',
      name: {
        nb: 'Vei',
        nn: 'Vei',
        en: 'Road',
      },
      layers: 't_vei',
      categoryId: 'accessibilityVillageSight',
      groupid: 8,
      legacyId: '1020',
      queryable: true,
    },
    {
      id: '8_t_HC_parkering',
      name: {
        nb: 'HC-parkering',
        nn: 'HC-parkering',
        en: 'HC-parking',
      },
      layers: 't_HC_parkering',
      categoryId: 'accessibilityVillageSight',
      groupid: 8,
      legacyId: '1021',
      queryable: true,
    },
    {
      id: '8_t_inngangbygg',
      name: {
        nb: 'Inngang bygg',
        nn: 'Inngang bygg',
        en: 'Bulding entrance',
      },
      layers: 't_inngangbygg',
      categoryId: 'accessibilityVillageSight',
      groupid: 8,
      legacyId: '1022',
      queryable: true,
    },
    {
      id: '5_statlig_sikra_polygon_01',
      name: {
        nb: 'Statlig sikra',
        nn: 'Statlig sikra',
        en: 'Secured by the state ',
      },
      layers: 'statlig_sikra_polygon_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1011',
      queryable: true,
    },
    {
      id: '5_friluftsomrade_01',
      name: {
        nb: 'Friluftsområde',
        nn: 'Friluftsområde',
        en: 'Recreational area',
      },
      layers: 'friluftsomrade_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1012',
      queryable: true,
    },
    {
      id: '5_parkeringsomrader_friluft_01',
      name: {
        nb: 'Parkeringsområder',
        nn: 'Parkeringsområder',
        en: 'Parking areas',
      },
      layers: 'parkeringsomrader_friluft_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1013',
      queryable: true,
    },
    {
      id: '5_turvei_01',
      name: {
        nb: 'Turvei',
        nn: 'Turvei',
        en: 'Hiking path',
      },
      layers: 'turvei_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1014',
      queryable: true,
    },
    {
      id: '5_turisthytte_01',
      name: {
        nb: 'Turisthytte',
        nn: 'Turisthytte',
        en: 'Tourist cabin',
      },
      layers: 'turisthytte_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1015',
      queryable: true,
    },
    {
      id: '5_gapahukhytte_01',
      name: {
        nb: 'Gapahukhytte',
        nn: 'Gapahukhytte',
        en: 'Lean-to shelter',
      },
      layers: 'gapahukhytte_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1016',
      queryable: true,
    },
    {
      id: '5_fiskeplass_01',
      name: {
        nb: 'Fiskeplass',
        nn: 'Fiskeplass',
        en: 'Fishing spot',
      },
      layers: 'fiskeplass_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1017',
      queryable: true,
    },
    {
      id: '5_grillbalplass_01',
      name: {
        nb: 'Grillbålplass',
        nn: 'Grillbålplass',
        en: 'BBQ fire pit',
      },
      layers: 'grillbalplass_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1018',
      queryable: true,
    },
    {
      id: '5_baderampe_01',
      name: {
        nb: 'Baderampe',
        nn: 'Baderampe',
        en: 'Swiming accessibility ramp',
      },
      layers: 'baderampe_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1019',
      queryable: true,
    },
    {
      id: '5_hc_parkering_friluft_01',
      name: {
        nb: 'HC-parkering',
        nn: 'HC-parkering',
        en: 'HC-parking',
      },
      layers: 'hc_parkering_friluft_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1020',
      queryable: true,
    },
    {
      id: '5_skiloype_01',
      name: {
        nb: 'Skiløype',
        nn: 'Skiløype',
        en: 'Cross country skiing route',
      },
      layers: 'skiloype_01',
      categoryId: 'accessibilityRecreationWheelchair',
      groupid: 5,
      legacyId: '1021',
      queryable: true,
    },
    {
      id: '7_statlig_sikra_polygon_02',
      name: {
        nb: 'Statlig sikra',
        nn: 'Statlig sikra',
        en: 'Secured by the state ',
      },
      layers: 'statlig_sikra_polygon_02',
      categoryId: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      legacyId: '1022',
      queryable: true,
    },
    {
      id: '7_friluftsomrade_02',
      name: {
        nb: 'Friluftsområde',
        nn: 'Friluftsområde',
        en: 'Recreational area',
      },
      layers: 'friluftsomrade_02',
      categoryId: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      legacyId: '1023',
      queryable: true,
    },
    {
      id: '7_parkeringsomrader_friluft_02',
      name: {
        nb: 'Parkeringsområder',
        nn: 'Parkeringsområder',
        en: 'Parking areas',
      },
      layers: 'parkeringsomrader_friluft_02',
      categoryId: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      legacyId: '1024',
      queryable: true,
    },
    {
      id: '7_turvei_02',
      name: {
        nb: 'Turvei',
        nn: 'Turvei',
        en: 'Hiking path',
      },
      layers: 'turvei_02',
      categoryId: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      legacyId: '1025',
      queryable: true,
    },
    {
      id: '7_turisthytte_02',
      name: {
        nb: 'turisthytte',
        nn: 'turisthytte',
        en: 'Tourist cabin',
      },
      layers: 'turisthytte_02',
      categoryId: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      legacyId: '1026',
      queryable: true,
    },
    {
      id: '7_gapahukhytte_02',
      name: {
        nb: 'Gapahukhytte',
        nn: 'Gapahukhytte',
        en: 'Lean-to shelter',
      },
      layers: 'gapahukhytte_02',
      categoryId: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      legacyId: '1027',
      queryable: true,
    },
    {
      id: '7_fiskeplass_02',
      name: {
        nb: 'Fiskeplass',
        nn: 'Fiskeplass',
        en: 'Fishing spot',
      },
      layers: 'fiskeplass_02',
      categoryId: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      legacyId: '1028',
      queryable: true,
    },
    {
      id: '7_grillbalplass_02',
      name: {
        nb: 'Grillbålplass',
        nn: 'Grillbålplass',
        en: 'BBQ fire pit',
      },
      layers: 'grillbalplass_02',
      categoryId: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      legacyId: '1029',
      queryable: true,
    },
    {
      id: '7_hc_parkering_friluft_02',
      name: {
        nb: 'HC-parkering',
        nn: 'HC-parkering',
        en: 'HC-parking',
      },
      layers: 'hc_parkering_friluft_02',
      categoryId: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      legacyId: '1030',
      queryable: true,
    },
    {
      id: '7_skiloype_02',
      name: {
        nb: 'Skiløype',
        nn: 'Skiløype',
        en: 'Cross country skiing route',
      },
      layers: 'skiloype_02',
      categoryId: 'accessibilityRecreationElectricWheelchair',
      groupid: 7,
      legacyId: '1031',
      queryable: true,
    },
    {
      id: '3_statlig_sikra_polygon_03',
      name: {
        nb: 'Statlig sikra',
        nn: 'Statlig sikra',
        en: 'Secured by the state ',
      },
      layers: 'statlig_sikra_polygon_03',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1032',
      queryable: true,
    },
    {
      id: '3_friluftsomrade_03',
      name: {
        nb: 'Friluftsområde',
        nn: 'Friluftsområde',
        en: 'Recreational area',
      },
      layers: 'friluftsomrade_03',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1033',
      queryable: true,
    },
    {
      id: '3_parkeringsomrader_friluft_03',
      name: {
        nb: 'Parkeringsområder',
        nn: 'Parkeringsområder',
        en: 'Parking areas',
      },
      layers: 'parkeringsomrader_friluft_03',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1034',
      queryable: true,
    },
    {
      id: '3_turvei_03',
      name: {
        nb: 'Turvei',
        nn: 'Turvei',
        en: 'Hiking path',
      },
      layers: 'turvei_03',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1035',
      queryable: true,
    },
    {
      id: '3_turisthytte_03',
      name: {
        nb: 'Turisthytte',
        nn: 'Turisthytte',
        en: 'Tourist cabin',
      },
      layers: 'turisthytte_03',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1036',
      queryable: true,
    },
    {
      id: '3_gapahukhytte_03',
      name: {
        nb: 'Gapahukhytte',
        nn: 'Gapahukhytte',
        en: 'Lean-to shelter',
      },
      layers: 'gapahukhytte_03',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1037',
      queryable: true,
    },
    {
      id: '3_fiskeplass_03',
      name: {
        nb: 'Fiskeplass',
        nn: 'Fiskeplass',
        en: 'Fishing spot',
      },
      layers: 'fiskeplass_03',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1038',
      queryable: true,
    },
    {
      id: '3_grillbalplass_03',
      name: {
        nb: 'Grillbålplass',
        nn: 'Grillbålplass',
        en: 'BBQ fire pit',
      },
      layers: 'grillbalplass_03',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1039',
      queryable: true,
    },
    {
      id: '3_baderampe_02',
      name: {
        nb: 'Baderampe',
        nn: 'Baderampe',
        en: 'Swiming accessibility ramp',
      },
      layers: 'baderampe_02',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1040',
      queryable: true,
    },
    {
      id: '3_hc_parkering_friluft_03',
      name: {
        nb: 'HC-parkering',
        nn: 'HC-parkering',
        en: 'HC-parking',
      },
      layers: 'hc_parkering_friluft_03',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1041',
      queryable: true,
    },
    {
      id: '3_skiloype_03',
      name: {
        nb: 'Skiløype',
        nn: 'Skiløype',
        en: 'Cross country skiing route',
      },
      layers: 'skiloype_03',
      categoryId: 'accessibilityRecreationSight',
      groupid: 3,
      legacyId: '1042',
      queryable: true,
    },
    {
      id: '10_toalett',
      name: {
        nb: 'Toalett',
        nn: 'Toalett',
        en: 'Toilet',
      },
      layers: 'toalett',
      categoryId: 'accessibilityShared',
      groupid: 10,
      legacyId: '1055',
      queryable: true,
    },
    {
      id: '10_sittegruppebenk',
      name: {
        nb: 'Sittegruppebenk',
        nn: 'Sittegruppebenk',
        en: 'Seating',
      },
      layers: 'sittegruppebenk',
      categoryId: 'accessibilityShared',
      groupid: 10,
      legacyId: '1056',
      queryable: true,
    },
  ],
};
