import { Box, HStack, IconButton, Portal, Stack, Tooltip } from '@kvib/react';
import { useAtomValue } from 'jotai';
import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { mapOrientationDegreesAtom } from './atoms';
import { useMapSettings } from './mapHooks';

export const MapOverlay = () => {
  const { setMapFullScreen, setMapLocation, setMapAngle, rotateSnappy } =
    useMapSettings();
  const mapOrientation = useAtomValue(mapOrientationDegreesAtom);
  const [portalTarget, setPortalTarget] = useState<HTMLElement | null>(null);
  const portalRef = useRef<HTMLElement>(null);
  const { t } = useTranslation();

  useEffect(() => {
    setTimeout(() => {
      const portalTargetElement = document.getElementById(
        'custom-control-portal',
      );
      portalRef.current = portalTargetElement;
      setPortalTarget(portalTargetElement);
    }, 10);
  }, []);

  //NOTE: Some of the overlay is generated by openlayers. See map.css for those styles.
  return (
    <>
      {portalTarget && (
        <Portal container={portalRef}>
          <Box position="absolute" bottom="16px" left="16px" zIndex={10}>
            <a
              href="https://www.kartverket.no"
              target="_blank"
              rel="noopener noreferrer"
            >
              <img
                src="/logos/KV_logo_staa.svg"
                alt="Logo"
                style={{ height: 64 }}
              />
            </a>
          </Box>
          <Box position={'absolute'} left={'10px'} top={'100px'} zIndex={10}>
            <HStack>
              <IconButton
                icon={'switch_access_shortcut'}
                variant="ghost"
                _hover={{ bg: 'transparent' }}
                m={0}
                p={0}
                onClick={() => {
                  rotateSnappy('right');
                }}
              />
              <IconButton
                icon={'navigation'}
                variant="ghost"
                _hover={{ bg: 'transparent' }}
                onClick={() => {
                  setMapAngle(0);
                }}
                m={0}
                p={0}
                rotate={mapOrientation + 'deg'}
              />
              <IconButton
                icon={'switch_access_shortcut'}
                variant="ghost"
                _hover={{ bg: 'transparent' }}
                transform={'scale(-1,1)'}
                m={0}
                p={0}
                onClick={() => {
                  rotateSnappy('left');
                }}
              />
            </HStack>
          </Box>
          <Box position="absolute" top="16px" right="16px" zIndex={10}>
            <Stack>
              {document.fullscreenEnabled && (
                <Tooltip content={t('map.overlay.fullscreen')}>
                  <IconButton
                    onClick={() => {
                      setMapFullScreen(true);
                    }}
                    variant="ghost"
                    icon={'fullscreen'}
                  />
                </Tooltip>
              )}
              <Tooltip content={t('map.overlay.myPosition')}>
                <IconButton
                  onClick={() => {
                    navigator.geolocation.getCurrentPosition((pos) => {
                      setMapLocation(
                        [pos.coords.longitude, pos.coords.latitude],
                        'EPSG:4326',
                        15,
                      );
                    });
                  }}
                  variant="ghost"
                  icon={'my_location'}
                />
              </Tooltip>
            </Stack>
          </Box>
        </Portal>
      )}
    </>
  );
};
