import { getEnv } from '../../../../env';
import { ThemeLayerConfig } from '../../themeLayerConfigApi';

// Grayscale ("graa") counterpart to topoQgis.ts — 25 of farge's 32 layers
// (only what exists as a graa/*.qlr file; see tnt-topo-qlr's graa/
// directory for which). Own dedicated pods (graa01-graa25, topo-graa
// namespace), same WMS layer names as farge (each pod only knows about its
// one layer locally). Keep in sync with tnt-apps' applications/
// qgis.libsonnet defaultGraaLayers.
const LAYER_POD: Record<string, string> = {
  lag01_hav: '01',
  lag02_dybdelag_gebco: '02',
  lag03_dybdelag_sjo: '03',
  lag04_Europa: '04',
  lag05_hoydelag: '05',
  lag06_arealdekke: '06',
  lag07_elveflate: '07',
  lag09_relieff_sol: '08',
  lag10_hoydekurve: '09',
  lag11_relieff_skygge_graa: '10',
  lag12_innsjoflate: '11',
  lag13_grense_adm_maritim_fare_naturvern: '12',
  lag14_vannkontur_elvbekk: '13',
  lag17_samferdsel_anlegg: '14',
  lag18_samferdsel_tunnel: '15',
  lag19_samferdsel_batrute: '16',
  lag20_samferdsel_terreng: '17',
  lag21_bygning_anlegg: '18',
  lag22_samferdsel_bru: '19',
  lag23_bygning_bygningslinje: '20',
  lag25_kraftlinje_taubane: '21',
  lag26_hoydepunkt: '22',
  lag27_sykehus_m_akuttmottak: '23',
  lag28_adm_grensepunkt: '24',
  lag29_hoydetall: '25',
  lag30_stedsnavn_vegnummer_og_adresse: '26',
};

// Independent of topoQgis's clusterDomain — graa only exists in dev so far,
const CLUSTER_DOMAIN = getEnv().layerProviderParameters.topoQgisGraa.clusterDomain;

const mapUrl = (name: string) =>
  `https://graa${LAYER_POD[name]}-qgis.${CLUSTER_DOMAIN}/qgis/QLR/${name}`;

export const topoQgisGraaConfig: ThemeLayerConfig = {
  categories: [
    {
      id: 'topoQgisGraa',
      groupid: 99,
      name: { nb: 'Topo QGIS (grå)', nn: 'Topo QGIS (grå)', en: 'Topo QGIS (gray)' },
    },
    {
      id: 'topoQgisGraa_lag01_hav',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Hav', nn: 'Hav', en: 'Sea' },
    },
    {
      id: 'topoQgisGraa_lag02_dybdelag_gebco',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Dybdelag GEBCO', nn: 'Djupnelag GEBCO', en: 'Depth GEBCO' },
    },
    {
      id: 'topoQgisGraa_lag03_dybdelag_sjo',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Dybdelag sjø', nn: 'Djupnelag sjø', en: 'Sea depth' },
    },
    {
      id: 'topoQgisGraa_lag04_Europa',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Europa', nn: 'Europa', en: 'Europe' },
    },
    {
      id: 'topoQgisGraa_lag05_hoydelag',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Høydelag', nn: 'Høgdelag', en: 'Elevation bands' },
    },
    {
      id: 'topoQgisGraa_lag06_arealdekke',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Arealdekke', nn: 'Arealdekke', en: 'Land cover' },
    },
    {
      id: 'topoQgisGraa_lag07_elveflate',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Elveflate', nn: 'Elveflate', en: 'River surface' },
    },
    {
      id: 'topoQgisGraa_lag09_relieff_sol',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Relieff sol', nn: 'Relieff sol', en: 'Relief (sun)' },
    },
    {
      id: 'topoQgisGraa_lag10_hoydekurve',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Høydekurve', nn: 'Høgdekurve', en: 'Contours' },
    },
    {
      id: 'topoQgisGraa_lag11_relieff_skygge_graa',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Relieff skygge blågrå',
        nn: 'Relieff skugge blågrå',
        en: 'Relief (shadow) blue-gray',
      },
    },
    {
      id: 'topoQgisGraa_lag12_innsjoflate',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Innsjøflate', nn: 'Innsjøflate', en: 'Lake surface' },
    },
    {
      id: 'topoQgisGraa_lag13_grense_adm_maritim_fare_naturvern',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Grense, adm., maritim, fare, naturvern',
        nn: 'Grense, adm., maritim, fare, naturvern',
        en: 'Boundaries, admin, maritime, hazard, nature',
      },
    },
    {
      id: 'topoQgisGraa_lag14_vannkontur_elvbekk',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Vannkontur, elv og bekk',
        nn: 'Vasskontur, elv og bekk',
        en: 'Water contour, rivers, streams',
      },
    },
    {
      id: 'topoQgisGraa_lag17_samferdsel_anlegg',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Samferdsel anlegg',
        nn: 'Samferdsel anlegg',
        en: 'Transport infrastructure',
      },
    },
    {
      id: 'topoQgisGraa_lag18_samferdsel_tunnel',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Samferdsel tunnel',
        nn: 'Samferdsel tunnel',
        en: 'Transport tunnels',
      },
    },
    {
      id: 'topoQgisGraa_lag19_samferdsel_batrute',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Båtrute', nn: 'Båtrute', en: 'Boat routes' },
    },
    {
      id: 'topoQgisGraa_lag20_samferdsel_terreng',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Samferdsel terreng',
        nn: 'Samferdsel terreng',
        en: 'Transport terrain',
      },
    },
    {
      id: 'topoQgisGraa_lag21_bygning_anlegg',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Bygning og anlegg',
        nn: 'Bygning og anlegg',
        en: 'Buildings and facilities',
      },
    },
    {
      id: 'topoQgisGraa_lag22_samferdsel_bru',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Bruer', nn: 'Bruer', en: 'Bridges' },
    },
    {
      id: 'topoQgisGraa_lag23_bygning_bygningslinje',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Bygningslinje', nn: 'Bygningslinje', en: 'Building lines' },
    },
    {
      id: 'topoQgisGraa_lag25_kraftlinje_taubane',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Kraftlinje og taubane',
        nn: 'Kraftlinje og taubane',
        en: 'Power lines and cable cars',
      },
    },
    {
      id: 'topoQgisGraa_lag26_hoydepunkt',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Høydepunkt', nn: 'Høgdepunkt', en: 'Elevation points' },
    },
    {
      id: 'topoQgisGraa_lag27_sykehus_m_akuttmottak',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Sykehus m/ akuttmottak',
        nn: 'Sjukehus m/ akuttmottak',
        en: 'Hospitals with A&E',
      },
    },
    {
      id: 'topoQgisGraa_lag28_adm_grensepunkt',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Adm. grensepunkt',
        nn: 'Adm. grensepunkt',
        en: 'Admin boundary points',
      },
    },
    {
      id: 'topoQgisGraa_lag29_hoydetall',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: { nb: 'Høydetall', nn: 'Høgdetallar', en: 'Elevation numbers' },
    },
    {
      id: 'topoQgisGraa_lag30_stedsnavn_vegnummer_og_adresse',
      groupid: 99,
      parentId: 'topoQgisGraa',
      name: {
        nb: 'Stedsnavn, vegnummer og adresse',
        nn: 'Stadnamn, vegnummer og adresse',
        en: 'Place names, road numbers and addresses',
      },
    },
  ],
  layers: [
    {
      id: 'topoQgisGraa_lag01_hav',
      categoryId: 'topoQgisGraa_lag01_hav',
      groupid: 99,
      name: { nb: 'Hav', nn: 'Hav', en: 'Sea' },
      wmsUrl: mapUrl('lag01_hav'),
      layers: 'lag01_hav',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag02_dybdelag_gebco',
      categoryId: 'topoQgisGraa_lag02_dybdelag_gebco',
      groupid: 99,
      name: { nb: 'Dybdelag GEBCO', nn: 'Djupnelag GEBCO', en: 'Depth GEBCO' },
      wmsUrl: mapUrl('lag02_dybdelag_gebco'),
      layers: 'lag02_dybdelag_gebco',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag03_dybdelag_sjo',
      categoryId: 'topoQgisGraa_lag03_dybdelag_sjo',
      groupid: 99,
      name: { nb: 'Dybdelag sjø', nn: 'Djupnelag sjø', en: 'Sea depth' },
      wmsUrl: mapUrl('lag03_dybdelag_sjo'),
      layers: 'lag03_dybdelag_sjo',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag04_Europa',
      categoryId: 'topoQgisGraa_lag04_Europa',
      groupid: 99,
      name: { nb: 'Europa', nn: 'Europa', en: 'Europe' },
      wmsUrl: mapUrl('lag04_Europa'),
      layers: 'lag04_Europa',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag05_hoydelag',
      categoryId: 'topoQgisGraa_lag05_hoydelag',
      groupid: 99,
      name: { nb: 'Høydelag', nn: 'Høgdelag', en: 'Elevation bands' },
      wmsUrl: mapUrl('lag05_hoydelag'),
      layers: 'lag05_hoydelag',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag06_arealdekke',
      categoryId: 'topoQgisGraa_lag06_arealdekke',
      groupid: 99,
      name: { nb: 'Arealdekke', nn: 'Arealdekke', en: 'Land cover' },
      wmsUrl: mapUrl('lag06_arealdekke'),
      layers: 'lag06_arealdekke',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag07_elveflate',
      categoryId: 'topoQgisGraa_lag07_elveflate',
      groupid: 99,
      name: { nb: 'Elveflate', nn: 'Elveflate', en: 'River surface' },
      wmsUrl: mapUrl('lag07_elveflate'),
      layers: 'lag07_elveflate',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag09_relieff_sol',
      categoryId: 'topoQgisGraa_lag09_relieff_sol',
      groupid: 99,
      name: { nb: 'Relieff sol', nn: 'Relieff sol', en: 'Relief (sun)' },
      wmsUrl: mapUrl('lag09_relieff_sol'),
      layers: 'lag09_relieff_sol',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag10_hoydekurve',
      categoryId: 'topoQgisGraa_lag10_hoydekurve',
      groupid: 99,
      name: { nb: 'Høydekurve', nn: 'Høgdekurve', en: 'Contours' },
      wmsUrl: mapUrl('lag10_hoydekurve'),
      layers: 'lag10_hoydekurve',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag11_relieff_skygge_graa',
      categoryId: 'topoQgisGraa_lag11_relieff_skygge_graa',
      groupid: 99,
      name: {
        nb: 'Relieff skygge blågrå',
        nn: 'Relieff skugge blågrå',
        en: 'Relief (shadow) blue-gray',
      },
      wmsUrl: mapUrl('lag11_relieff_skygge_graa'),
      layers: 'lag11_relieff_skygge_graa',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag12_innsjoflate',
      categoryId: 'topoQgisGraa_lag12_innsjoflate',
      groupid: 99,
      name: { nb: 'Innsjøflate', nn: 'Innsjøflate', en: 'Lake surface' },
      wmsUrl: mapUrl('lag12_innsjoflate'),
      layers: 'lag12_innsjoflate',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag13_grense_adm_maritim_fare_naturvern',
      categoryId: 'topoQgisGraa_lag13_grense_adm_maritim_fare_naturvern',
      groupid: 99,
      name: {
        nb: 'Grense, adm., maritim, fare, naturvern',
        nn: 'Grense, adm., maritim, fare, naturvern',
        en: 'Boundaries, admin, maritime, hazard, nature',
      },
      wmsUrl: mapUrl('lag13_grense_adm_maritim_fare_naturvern'),
      layers: 'lag13_grense_adm_maritim_fare_naturvern',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag14_vannkontur_elvbekk',
      categoryId: 'topoQgisGraa_lag14_vannkontur_elvbekk',
      groupid: 99,
      name: {
        nb: 'Vannkontur, elv og bekk',
        nn: 'Vasskontur, elv og bekk',
        en: 'Water contour, rivers, streams',
      },
      wmsUrl: mapUrl('lag14_vannkontur_elvbekk'),
      layers: 'lag14_vannkontur_elvbekk',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag17_samferdsel_anlegg',
      categoryId: 'topoQgisGraa_lag17_samferdsel_anlegg',
      groupid: 99,
      name: {
        nb: 'Samferdsel anlegg',
        nn: 'Samferdsel anlegg',
        en: 'Transport infrastructure',
      },
      wmsUrl: mapUrl('lag17_samferdsel_anlegg'),
      layers: 'lag17_samferdsel_anlegg',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag18_samferdsel_tunnel',
      categoryId: 'topoQgisGraa_lag18_samferdsel_tunnel',
      groupid: 99,
      name: {
        nb: 'Samferdsel tunnel',
        nn: 'Samferdsel tunnel',
        en: 'Transport tunnels',
      },
      wmsUrl: mapUrl('lag18_samferdsel_tunnel'),
      layers: 'lag18_samferdsel_tunnel',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag19_samferdsel_batrute',
      categoryId: 'topoQgisGraa_lag19_samferdsel_batrute',
      groupid: 99,
      name: { nb: 'Båtrute', nn: 'Båtrute', en: 'Boat routes' },
      wmsUrl: mapUrl('lag19_samferdsel_batrute'),
      layers: 'lag19_samferdsel_batrute',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag20_samferdsel_terreng',
      categoryId: 'topoQgisGraa_lag20_samferdsel_terreng',
      groupid: 99,
      name: {
        nb: 'Samferdsel terreng',
        nn: 'Samferdsel terreng',
        en: 'Transport terrain',
      },
      wmsUrl: mapUrl('lag20_samferdsel_terreng'),
      layers: 'lag20_samferdsel_terreng',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag21_bygning_anlegg',
      categoryId: 'topoQgisGraa_lag21_bygning_anlegg',
      groupid: 99,
      name: {
        nb: 'Bygning og anlegg',
        nn: 'Bygning og anlegg',
        en: 'Buildings and facilities',
      },
      wmsUrl: mapUrl('lag21_bygning_anlegg'),
      layers: 'lag21_bygning_anlegg',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag22_samferdsel_bru',
      categoryId: 'topoQgisGraa_lag22_samferdsel_bru',
      groupid: 99,
      name: { nb: 'Bruer', nn: 'Bruer', en: 'Bridges' },
      wmsUrl: mapUrl('lag22_samferdsel_bru'),
      layers: 'lag22_samferdsel_bru',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag23_bygning_bygningslinje',
      categoryId: 'topoQgisGraa_lag23_bygning_bygningslinje',
      groupid: 99,
      name: { nb: 'Bygningslinje', nn: 'Bygningslinje', en: 'Building lines' },
      wmsUrl: mapUrl('lag23_bygning_bygningslinje'),
      layers: 'lag23_bygning_bygningslinje',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag25_kraftlinje_taubane',
      categoryId: 'topoQgisGraa_lag25_kraftlinje_taubane',
      groupid: 99,
      name: {
        nb: 'Kraftlinje og taubane',
        nn: 'Kraftlinje og taubane',
        en: 'Power lines and cable cars',
      },
      wmsUrl: mapUrl('lag25_kraftlinje_taubane'),
      layers: 'lag25_kraftlinje_taubane',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag26_hoydepunkt',
      categoryId: 'topoQgisGraa_lag26_hoydepunkt',
      groupid: 99,
      name: { nb: 'Høydepunkt', nn: 'Høgdepunkt', en: 'Elevation points' },
      wmsUrl: mapUrl('lag26_hoydepunkt'),
      layers: 'lag26_hoydepunkt',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag27_sykehus_m_akuttmottak',
      categoryId: 'topoQgisGraa_lag27_sykehus_m_akuttmottak',
      groupid: 99,
      name: {
        nb: 'Sykehus m/ akuttmottak',
        nn: 'Sjukehus m/ akuttmottak',
        en: 'Hospitals with A&E',
      },
      wmsUrl: mapUrl('lag27_sykehus_m_akuttmottak'),
      layers: 'lag27_sykehus_m_akuttmottak',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag28_adm_grensepunkt',
      categoryId: 'topoQgisGraa_lag28_adm_grensepunkt',
      groupid: 99,
      name: {
        nb: 'Adm. grensepunkt',
        nn: 'Adm. grensepunkt',
        en: 'Admin boundary points',
      },
      wmsUrl: mapUrl('lag28_adm_grensepunkt'),
      layers: 'lag28_adm_grensepunkt',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag29_hoydetall',
      categoryId: 'topoQgisGraa_lag29_hoydetall',
      groupid: 99,
      name: { nb: 'Høydetall', nn: 'Høgdetallar', en: 'Elevation numbers' },
      wmsUrl: mapUrl('lag29_hoydetall'),
      layers: 'lag29_hoydetall',
      singleImage: true,
      useLegendGraphic: true,
    },
    {
      id: 'topoQgisGraa_lag30_stedsnavn_vegnummer_og_adresse',
      categoryId: 'topoQgisGraa_lag30_stedsnavn_vegnummer_og_adresse',
      groupid: 99,
      name: {
        nb: 'Stedsnavn, vegnummer og adresse',
        nn: 'Stadnamn, vegnummer og adresse',
        en: 'Place names, road numbers and addresses',
      },
      wmsUrl: mapUrl('lag30_stedsnavn_vegnummer_og_adresse'),
      layers: 'lag30_stedsnavn_vegnummer_og_adresse',
      singleImage: true,
      useLegendGraphic: true,
    },
  ],
};
