import { getEnv } from '../../../../env';
import { ThemeLayerConfig } from '../../themeLayerConfigApi';

const QGIS_BASE = getEnv().layerProviderParameters.topoQgis.baseUrl;

const mapUrl = (name: string) =>
  `${QGIS_BASE}/qgis/QLR/${name}`;

export const topoQgisConfig: ThemeLayerConfig = {
  categories: [
    {
      id: 'topoQgis',
      groupid: 99,
      name: { nb: 'Topo QGIS', nn: 'Topo QGIS', en: 'Topo QGIS' },
    },
    {
      id: 'topoQgis_lag01_hav',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Hav', nn: 'Hav', en: 'Sea' },
    },
    {
      id: 'topoQgis_lag02_dybdelag_gebco',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Dybdelag GEBCO', nn: 'Djupnelag GEBCO', en: 'Depth GEBCO' },
    },
    {
      id: 'topoQgis_lag03_dybdelag_sjo',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Dybdelag sjø', nn: 'Djupnelag sjø', en: 'Sea depth' },
    },
    {
      id: 'topoQgis_lag04_Europa',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Europa', nn: 'Europa', en: 'Europe' },
    },
    {
      id: 'topoQgis_lag05_hoydelag',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Høydelag', nn: 'Høgdelag', en: 'Elevation bands' },
    },
    {
      id: 'topoQgis_lag06_arealdekke',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Arealdekke', nn: 'Arealdekke', en: 'Land cover' },
    },
    {
      id: 'topoQgis_lag07_elveflate',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Elveflate', nn: 'Elveflate', en: 'River surface' },
    },
    {
      id: 'topoQgis_lag08_sjodybde',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Sjødybde', nn: 'Sjødjupne', en: 'Sea depth data' },
    },
    {
      id: 'topoQgis_lag09_relieff_sol',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Relieff sol', nn: 'Relieff sol', en: 'Relief (sun)' },
    },
    {
      id: 'topoQgis_lag10_hoydekurve',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Høydekurve', nn: 'Høgdekurve', en: 'Contours' },
    },
    {
      id: 'topoQgis_lag11_relieff_skygge',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Relieff skygge', nn: 'Relieff skugge', en: 'Relief (shadow)' },
    },
    {
      id: 'topoQgis_lag12_innsjoflate',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Innsjøflate', nn: 'Innsjøflate', en: 'Lake surface' },
    },
    {
      id: 'topoQgis_lag13_grense_adm_maritim_fare_naturvern',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Grense, adm., maritim, fare, naturvern', nn: 'Grense, adm., maritim, fare, naturvern', en: 'Boundaries, admin, maritime, hazard, nature' },
    },
    {
      id: 'topoQgis_lag14_vannkontur_elvbekk',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Vannkontur, elv og bekk', nn: 'Vasskontur, elv og bekk', en: 'Water contour, rivers, streams' },
    },
    {
      id: 'topoQgis_lag15_fkb_bygnanlegg',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'FKB bygg og anlegg', nn: 'FKB bygg og anlegg', en: 'FKB buildings and infrastructure' },
    },
    {
      id: 'topoQgis_lag16_fkb_samferdselflate_terreng',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'FKB samferdselflate terreng', nn: 'FKB samferdselflate terreng', en: 'FKB transport surface terrain' },
    },
    {
      id: 'topoQgis_lag17_samferdsel_anlegg',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Samferdsel anlegg', nn: 'Samferdsel anlegg', en: 'Transport infrastructure' },
    },
    {
      id: 'topoQgis_lag18_samferdsel_tunnel',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Samferdsel tunnel', nn: 'Samferdsel tunnel', en: 'Transport tunnels' },
    },
    {
      id: 'topoQgis_lag19_samferdsel_batrute',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Båtrute', nn: 'Båtrute', en: 'Boat routes' },
    },
    {
      id: 'topoQgis_lag20_samferdsel_terreng',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Samferdsel terreng', nn: 'Samferdsel terreng', en: 'Transport terrain' },
    },
    {
      id: 'topoQgis_lag21_bygning_anlegg',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Bygning og anlegg', nn: 'Bygning og anlegg', en: 'Buildings and facilities' },
    },
    {
      id: 'topoQgis_lag22_samferdsel_bru',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Bruer', nn: 'Bruer', en: 'Bridges' },
    },
    {
      id: 'topoQgis_lag23_bygning_bygningslinje',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Bygningslinje', nn: 'Bygningslinje', en: 'Building lines' },
    },
    {
      id: 'topoQgis_lag24_lufthavn_S3',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Lufthavn S3', nn: 'Lufthamn S3', en: 'Airport S3' },
    },
    {
      id: 'topoQgis_lag25_kraftlinje_taubane',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Kraftlinje og taubane', nn: 'Kraftlinje og taubane', en: 'Power lines and cable cars' },
    },
    {
      id: 'topoQgis_lag26_hoydepunkt',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Høydepunkt', nn: 'Høgdepunkt', en: 'Elevation points' },
    },
    {
      id: 'topoQgis_lag27_sykehus_m_akuttmottak',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Sykehus m/ akuttmottak', nn: 'Sjukehus m/ akuttmottak', en: 'Hospitals with A&E' },
    },
    {
      id: 'topoQgis_lag28_adm_grensepunkt',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Adm. grensepunkt', nn: 'Adm. grensepunkt', en: 'Admin boundary points' },
    },
    {
      id: 'topoQgis_lag29_hoydetall',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Høydetall', nn: 'Høgdetallar', en: 'Elevation numbers' },
    },
    {
      id: 'topoQgis_lag30_stedsnavn_vegnummer_og_adresse',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Stedsnavn, vegnummer og adresse', nn: 'Stadnamn, vegnummer og adresse', en: 'Place names, road numbers and addresses' },
    },
    {
      id: 'topoQgis_lag31_Svalbard',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Svalbard', nn: 'Svalbard', en: 'Svalbard' },
    },
    {
      id: 'topoQgis_lag32_Jan_Mayen',
      groupid: 99,
      parentId: 'topoQgis',
      name: { nb: 'Jan Mayen', nn: 'Jan Mayen', en: 'Jan Mayen' },
    },
  ],
  layers: [
    {
      id: 'topoQgis_lag01_hav',
      categoryId: 'topoQgis_lag01_hav',
      groupid: 99,
      name: { nb: 'Hav', nn: 'Hav', en: 'Sea' },
      wmsUrl: mapUrl('lag01_hav'),
      layers: 'lag01_hav',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag02_dybdelag_gebco',
      categoryId: 'topoQgis_lag02_dybdelag_gebco',
      groupid: 99,
      name: { nb: 'Dybdelag GEBCO', nn: 'Djupnelag GEBCO', en: 'Depth GEBCO' },
      wmsUrl: mapUrl('lag02_dybdelag_gebco'),
      layers: 'lag02_dybdelag_gebco',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag03_dybdelag_sjo',
      categoryId: 'topoQgis_lag03_dybdelag_sjo',
      groupid: 99,
      name: { nb: 'Dybdelag sjø', nn: 'Djupnelag sjø', en: 'Sea depth' },
      wmsUrl: mapUrl('lag03_dybdelag_sjo'),
      layers: 'lag03_dybdelag_sjo',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag04_Europa',
      categoryId: 'topoQgis_lag04_Europa',
      groupid: 99,
      name: { nb: 'Europa', nn: 'Europa', en: 'Europe' },
      wmsUrl: mapUrl('lag04_Europa'),
      layers: 'lag04_Europa',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag05_hoydelag',
      categoryId: 'topoQgis_lag05_hoydelag',
      groupid: 99,
      name: { nb: 'Høydelag', nn: 'Høgdelag', en: 'Elevation bands' },
      wmsUrl: mapUrl('lag05_hoydelag'),
      layers: 'lag05_hoydelag',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag06_arealdekke',
      categoryId: 'topoQgis_lag06_arealdekke',
      groupid: 99,
      name: { nb: 'Arealdekke', nn: 'Arealdekke', en: 'Land cover' },
      wmsUrl: mapUrl('lag06_arealdekke'),
      layers: 'lag06_arealdekke',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag07_elveflate',
      categoryId: 'topoQgis_lag07_elveflate',
      groupid: 99,
      name: { nb: 'Elveflate', nn: 'Elveflate', en: 'River surface' },
      wmsUrl: mapUrl('lag07_elveflate'),
      layers: 'lag07_elveflate',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag08_sjodybde',
      categoryId: 'topoQgis_lag08_sjodybde',
      groupid: 99,
      name: { nb: 'Sjødybde', nn: 'Sjødjupne', en: 'Sea depth data' },
      wmsUrl: mapUrl('lag08_sjodybde'),
      layers: 'lag08_sjodybde',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag09_relieff_sol',
      categoryId: 'topoQgis_lag09_relieff_sol',
      groupid: 99,
      name: { nb: 'Relieff sol', nn: 'Relieff sol', en: 'Relief (sun)' },
      wmsUrl: mapUrl('lag09_relieff_sol'),
      layers: 'lag09_relieff_sol',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag10_hoydekurve',
      categoryId: 'topoQgis_lag10_hoydekurve',
      groupid: 99,
      name: { nb: 'Høydekurve', nn: 'Høgdekurve', en: 'Contours' },
      wmsUrl: mapUrl('lag10_hoydekurve'),
      layers: 'lag10_hoydekurve',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag11_relieff_skygge',
      categoryId: 'topoQgis_lag11_relieff_skygge',
      groupid: 99,
      name: { nb: 'Relieff skygge', nn: 'Relieff skugge', en: 'Relief (shadow)' },
      wmsUrl: mapUrl('lag11_relieff_skygge'),
      layers: 'lag11_relieff_skygge',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag12_innsjoflate',
      categoryId: 'topoQgis_lag12_innsjoflate',
      groupid: 99,
      name: { nb: 'Innsjøflate', nn: 'Innsjøflate', en: 'Lake surface' },
      wmsUrl: mapUrl('lag12_innsjoflate'),
      layers: 'lag12_innsjoflate',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag13_grense_adm_maritim_fare_naturvern',
      categoryId: 'topoQgis_lag13_grense_adm_maritim_fare_naturvern',
      groupid: 99,
      name: { nb: 'Grense, adm., maritim, fare, naturvern', nn: 'Grense, adm., maritim, fare, naturvern', en: 'Boundaries, admin, maritime, hazard, nature' },
      wmsUrl: mapUrl('lag13_grense_adm_maritim_fare_naturvern'),
      layers: 'lag13_grense_adm_maritim_fare_naturvern',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag14_vannkontur_elvbekk',
      categoryId: 'topoQgis_lag14_vannkontur_elvbekk',
      groupid: 99,
      name: { nb: 'Vannkontur, elv og bekk', nn: 'Vasskontur, elv og bekk', en: 'Water contour, rivers, streams' },
      wmsUrl: mapUrl('lag14_vannkontur_elvbekk'),
      layers: 'lag14_vannkontur_elvbekk',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag15_fkb_bygnanlegg',
      categoryId: 'topoQgis_lag15_fkb_bygnanlegg',
      groupid: 99,
      name: { nb: 'FKB bygg og anlegg', nn: 'FKB bygg og anlegg', en: 'FKB buildings and infrastructure' },
      wmsUrl: mapUrl('lag15_fkb_bygnanlegg'),
      layers: 'lag15_fkb_bygnanlegg',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag16_fkb_samferdselflate_terreng',
      categoryId: 'topoQgis_lag16_fkb_samferdselflate_terreng',
      groupid: 99,
      name: { nb: 'FKB samferdselflate terreng', nn: 'FKB samferdselflate terreng', en: 'FKB transport surface terrain' },
      wmsUrl: mapUrl('lag16_fkb_samferdselflate_terreng'),
      layers: 'lag16_fkb_samferdselflate_terreng',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag17_samferdsel_anlegg',
      categoryId: 'topoQgis_lag17_samferdsel_anlegg',
      groupid: 99,
      name: { nb: 'Samferdsel anlegg', nn: 'Samferdsel anlegg', en: 'Transport infrastructure' },
      wmsUrl: mapUrl('lag17_samferdsel_anlegg'),
      layers: 'lag17_samferdsel_anlegg',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag18_samferdsel_tunnel',
      categoryId: 'topoQgis_lag18_samferdsel_tunnel',
      groupid: 99,
      name: { nb: 'Samferdsel tunnel', nn: 'Samferdsel tunnel', en: 'Transport tunnels' },
      wmsUrl: mapUrl('lag18_samferdsel_tunnel'),
      layers: 'lag18_samferdsel_tunnel',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag19_samferdsel_batrute',
      categoryId: 'topoQgis_lag19_samferdsel_batrute',
      groupid: 99,
      name: { nb: 'Båtrute', nn: 'Båtrute', en: 'Boat routes' },
      wmsUrl: mapUrl('lag19_samferdsel_batrute'),
      layers: 'lag19_samferdsel_batrute',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag20_samferdsel_terreng',
      categoryId: 'topoQgis_lag20_samferdsel_terreng',
      groupid: 99,
      name: { nb: 'Samferdsel terreng', nn: 'Samferdsel terreng', en: 'Transport terrain' },
      wmsUrl: mapUrl('lag20_samferdsel_terreng'),
      layers: 'lag20_samferdsel_terreng',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag21_bygning_anlegg',
      categoryId: 'topoQgis_lag21_bygning_anlegg',
      groupid: 99,
      name: { nb: 'Bygning og anlegg', nn: 'Bygning og anlegg', en: 'Buildings and facilities' },
      wmsUrl: mapUrl('lag21_bygning_anlegg'),
      layers: 'lag21_bygning_anlegg',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag22_samferdsel_bru',
      categoryId: 'topoQgis_lag22_samferdsel_bru',
      groupid: 99,
      name: { nb: 'Bruer', nn: 'Bruer', en: 'Bridges' },
      wmsUrl: mapUrl('lag22_samferdsel_bru'),
      layers: 'lag22_samferdsel_bru',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag23_bygning_bygningslinje',
      categoryId: 'topoQgis_lag23_bygning_bygningslinje',
      groupid: 99,
      name: { nb: 'Bygningslinje', nn: 'Bygningslinje', en: 'Building lines' },
      wmsUrl: mapUrl('lag23_bygning_bygningslinje'),
      layers: 'lag23_bygning_bygningslinje',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag24_lufthavn_S3',
      categoryId: 'topoQgis_lag24_lufthavn_S3',
      groupid: 99,
      name: { nb: 'Lufthavn S3', nn: 'Lufthamn S3', en: 'Airport S3' },
      wmsUrl: mapUrl('lag24_lufthavn_S3'),
      layers: 'lag24_lufthavn_S3',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag25_kraftlinje_taubane',
      categoryId: 'topoQgis_lag25_kraftlinje_taubane',
      groupid: 99,
      name: { nb: 'Kraftlinje og taubane', nn: 'Kraftlinje og taubane', en: 'Power lines and cable cars' },
      wmsUrl: mapUrl('lag25_kraftlinje_taubane'),
      layers: 'lag25_kraftlinje_taubane',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag26_hoydepunkt',
      categoryId: 'topoQgis_lag26_hoydepunkt',
      groupid: 99,
      name: { nb: 'Høydepunkt', nn: 'Høgdepunkt', en: 'Elevation points' },
      wmsUrl: mapUrl('lag26_hoydepunkt'),
      layers: 'lag26_hoydepunkt',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag27_sykehus_m_akuttmottak',
      categoryId: 'topoQgis_lag27_sykehus_m_akuttmottak',
      groupid: 99,
      name: { nb: 'Sykehus m/ akuttmottak', nn: 'Sjukehus m/ akuttmottak', en: 'Hospitals with A&E' },
      wmsUrl: mapUrl('lag27_sykehus_m_akuttmottak'),
      layers: 'lag27_sykehus_m_akuttmottak',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag28_adm_grensepunkt',
      categoryId: 'topoQgis_lag28_adm_grensepunkt',
      groupid: 99,
      name: { nb: 'Adm. grensepunkt', nn: 'Adm. grensepunkt', en: 'Admin boundary points' },
      wmsUrl: mapUrl('lag28_adm_grensepunkt'),
      layers: 'lag28_adm_grensepunkt',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag29_hoydetall',
      categoryId: 'topoQgis_lag29_hoydetall',
      groupid: 99,
      name: { nb: 'Høydetall', nn: 'Høgdetallar', en: 'Elevation numbers' },
      wmsUrl: mapUrl('lag29_hoydetall'),
      layers: 'lag29_hoydetall',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag30_stedsnavn_vegnummer_og_adresse',
      categoryId: 'topoQgis_lag30_stedsnavn_vegnummer_og_adresse',
      groupid: 99,
      name: { nb: 'Stedsnavn, vegnummer og adresse', nn: 'Stadnamn, vegnummer og adresse', en: 'Place names, road numbers and addresses' },
      wmsUrl: mapUrl('lag30_stedsnavn_vegnummer_og_adresse'),
      layers: 'lag30_stedsnavn_vegnummer_og_adresse',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag31_Svalbard',
      categoryId: 'topoQgis_lag31_Svalbard',
      groupid: 99,
      name: { nb: 'Svalbard', nn: 'Svalbard', en: 'Svalbard' },
      wmsUrl: mapUrl('lag31_Svalbard'),
      layers: 'lag31_Svalbard',
      singleImage: true,
    },
    {
      id: 'topoQgis_lag32_Jan_Mayen',
      categoryId: 'topoQgis_lag32_Jan_Mayen',
      groupid: 99,
      name: { nb: 'Jan Mayen', nn: 'Jan Mayen', en: 'Jan Mayen' },
      wmsUrl: mapUrl('lag32_Jan_Mayen'),
      layers: 'lag32_Jan_Mayen',
      singleImage: true,
    },
  ],
};
