import {
  Box,
  createListCollection,
  FieldLabel,
  FieldRoot,
  Flex,
  Heading,
  IconButton,
  Input,
  InputGroup,
  SelectContent,
  SelectItem,
  SelectLabel,
  SelectRoot,
  SelectTrigger,
  SelectValueText,
  Separator,
  Spinner,
  Text,
  Tooltip,
  VStack,
} from '@kvib/react';
import { useAtomValue, useSetAtom } from 'jotai';
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { mapAtom } from '../../../map/atoms';
import {
  assignZIndices,
  createUrlWmsLayer,
  urlWmsLayersAtom,
} from '../../../map/layers/urlWms';

/**
 * Pre-verified Geonorge WMS layers, generated by
 * scripts/generateGeonorgeWmsLayers.js (`npm run geonorge-wms`).
 */
type GeonorgeWmsLayer = {
  id: string;
  title: string;
  organization: string;
  category: string;
  url: string;
  layer: string;
  detailsUrl: string | null;
  type: string;
};

// Order of the nasjonal temainndeling on geonorge.no/kartdata/datasett-i-geonorge/.
const CATEGORY_ORDER = [
  'basisGeodata',
  'befolkning',
  'eiendom',
  'energi',
  'flyfoto',
  'forurensning',
  'friluftsliv',
  'geologi',
  'hoydedata',
  'kulturminner',
  'kystOgFiskeri',
  'landbruk',
  'landskap',
  'natur',
  'plan',
  'samferdsel',
  'samfunnssikkerhet',
  'varOgKlima',
  'annet',
];
const ALL_CATEGORIES = 'all';
const MAX_VISIBLE_RESULTS = 50;
const MIN_QUERY_LENGTH = 2;

// ~200 kB, so only fetched once the section is opened.
const loadLayers = async (): Promise<GeonorgeWmsLayer[]> =>
  (await import('./geonorgeWmsLayers.json')).default.layers;

export const GeonorgeWmsSearch = () => {
  const { t } = useTranslation();
  const [layers, setLayers] = useState<GeonorgeWmsLayer[] | null>(null);
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState(ALL_CATEGORIES);
  const [addingId, setAddingId] = useState<string | null>(null);
  const [addedIds, setAddedIds] = useState<Set<string>>(new Set());
  const [addError, setAddError] = useState<string | null>(null);

  const map = useAtomValue(mapAtom);
  const setUrlWmsLayers = useSetAtom(urlWmsLayersAtom);
  const urlWmsLayers = useAtomValue(urlWmsLayersAtom);

  useEffect(() => {
    void loadLayers().then(setLayers);
  }, []);

  const categoryCollection = useMemo(() => {
    const present = new Set(layers?.map((l) => l.category));
    const items = [
      {
        value: ALL_CATEGORIES,
        label: t('map.settings.layers.theme.geonorgeSearch.allCategories'),
      },
      ...CATEGORY_ORDER.filter((c) => present.has(c)).map((c) => ({
        value: c,
        label: t(`map.settings.layers.theme.geonorgeSearch.categories.${c}`),
      })),
    ];
    return createListCollection({ items });
  }, [layers, t]);

  const trimmedQuery = query.trim().toLowerCase();
  const isFiltering =
    category !== ALL_CATEGORIES || trimmedQuery.length >= MIN_QUERY_LENGTH;
  const results = useMemo(() => {
    if (!layers || !isFiltering) return [];
    return layers.filter(
      (l) =>
        (category === ALL_CATEGORIES || l.category === category) &&
        (l.title.toLowerCase().includes(trimmedQuery) ||
          l.organization.toLowerCase().includes(trimmedQuery)),
    );
  }, [layers, category, trimmedQuery, isFiltering]);

  const handleAdd = async (entry: GeonorgeWmsLayer) => {
    setAddingId(entry.id);
    setAddError(null);
    try {
      const mapProjection = map.getView().getProjection().getCode();
      const layer = await createUrlWmsLayer(
        entry.url,
        entry.layer,
        mapProjection,
        urlWmsLayers.length,
      );
      if (!layer) {
        setAddError(t('map.settings.layers.theme.geonorgeSearch.addError'));
        return;
      }
      layer.set('layerTitle', entry.title);
      if (entry.detailsUrl) {
        layer.set('geonorgeDetailsUrl', entry.detailsUrl);
      }
      map.addLayer(layer);
      setUrlWmsLayers((prev) => {
        const next = [...prev, layer];
        assignZIndices(next);
        return next;
      });
      setAddedIds((prev) => new Set(prev).add(entry.id));
    } catch {
      setAddError(t('map.settings.layers.theme.geonorgeSearch.addError'));
    } finally {
      setAddingId(null);
    }
  };

  return (
    <Box marginTop={4}>
      <Separator marginBottom={3} />
      <Heading size={{ base: 'xs', md: 'sm' }} marginBottom={2}>
        {t('map.settings.layers.theme.geonorgeSearch.heading')}
      </Heading>

      {/* Labels, not placeholders, carry the field purpose (design.kartverket.no
          Search/skjemakomponenter); role="search" makes it a landmark. */}
      <VStack align="stretch" gap={2} role="search">
        <SelectRoot
          size="sm"
          collection={categoryCollection}
          value={[category]}
          onValueChange={(details) => {
            if (details.value.length > 0) setCategory(details.value[0]);
          }}
          disabled={!layers}
        >
          <SelectLabel fontSize="xs">
            {t('map.settings.layers.theme.geonorgeSearch.categoryLabel')}
          </SelectLabel>
          <SelectTrigger>
            <SelectValueText />
          </SelectTrigger>
          <SelectContent>
            {categoryCollection.items.map((item) => (
              <SelectItem key={item.value} item={item}>
                {item.label}
              </SelectItem>
            ))}
          </SelectContent>
        </SelectRoot>

        <FieldRoot disabled={!layers}>
          <FieldLabel fontSize="xs">
            {t('map.settings.layers.theme.geonorgeSearch.filterLabel')}
          </FieldLabel>
          <InputGroup endElement={!layers ? <Spinner size="xs" /> : undefined}>
            <Input
              size="sm"
              type="search"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
            />
          </InputGroup>
        </FieldRoot>
      </VStack>

      {/* Filtering is live, so result/error messages must be announced. */}
      <Box aria-live="polite">
        {isFiltering && layers && results.length === 0 && (
          <Text fontSize="xs" color="gray.500" marginTop={2}>
            {t('map.settings.layers.theme.geonorgeSearch.noResults')}
          </Text>
        )}

        {results.length > MAX_VISIBLE_RESULTS && (
          <Text fontSize="xs" color="gray.500" marginTop={2}>
            {t('map.settings.layers.theme.geonorgeSearch.tooManyResults', {
              shown: MAX_VISIBLE_RESULTS,
              total: results.length,
            })}
          </Text>
        )}

        {addError && (
          <Text fontSize="xs" color="red.500" marginTop={2}>
            {addError}
          </Text>
        )}
      </Box>

      {results.length > 0 && (
        <VStack
          align="stretch"
          gap={0}
          marginTop={2}
          maxH="240px"
          overflowY="auto"
        >
          {results.slice(0, MAX_VISIBLE_RESULTS).map((entry) => {
            const isAdded = addedIds.has(entry.id);
            const isAdding = addingId === entry.id;
            return (
              <Flex
                key={entry.id}
                align="center"
                gap={2}
                py={1.5}
                px={1}
                borderRadius="md"
                _hover={{ bg: 'gray.50' }}
              >
                <Box flex={1} minW={0}>
                  <Text
                    fontSize="xs"
                    fontWeight="medium"
                    lineClamp={1}
                    title={entry.title}
                  >
                    {entry.title}
                  </Text>
                  {entry.organization && (
                    <Text fontSize="xs" color="gray.500" lineClamp={1}>
                      {entry.organization}
                    </Text>
                  )}
                </Box>
                <Tooltip
                  content={
                    isAdded
                      ? t('map.settings.layers.theme.geonorgeSearch.added')
                      : t('map.settings.layers.theme.geonorgeSearch.addButton')
                  }
                >
                  <IconButton
                    size="xs"
                    variant="ghost"
                    icon={isAdded ? 'check' : 'add'}
                    aria-label={t(
                      'map.settings.layers.theme.geonorgeSearch.addButton',
                    )}
                    colorPalette={isAdded ? 'green' : 'blue'}
                    disabled={isAdded || isAdding}
                    onClick={() => void handleAdd(entry)}
                  >
                    {isAdding && <Spinner size="xs" />}
                  </IconButton>
                </Tooltip>
              </Flex>
            );
          })}
        </VStack>
      )}
    </Box>
  );
};
